spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ftrial?autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  session:
    store-type: NONE

security:
  basic:
    enabled: true
  oauth2:
    client:
      client-id: imooc
      client-secret: imoocSecret

server:
  port: 8080

swagger:
  enable: true

ryan:
  security:
    social:
      qq:
        app-id:
        app-secret:
    browser:
      loginPage: /demo-signIn.html
      loginType: JSON
    code:
      image:
        length: 3
        width: 100
        url: /order
      sms:
        url: /order





