spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ftrial?autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  session:
    store-type: NONE

security:
  basic:
    enabled: true

server:
  port: 8080

swagger:
  enable: true

ryan:
  security:
    browser:
      loginPage: /demo-signIn.html



